### ISSUE TITLE
RuntimeError when attempting to start recode via python modules

### ISSUE THREAD

**Issue by overestimate** [MCsniperPY/MCsniperPY#39]
`python -m mcsniperpy` results in this
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\User\MCsniperPY\mcsniperpy\__init__.py", line 4, in <module>
    from .cli import cli
  File "C:\Users\User\MCsniperPY\mcsniperpy\cli.py", line 27, in <module>
    sniper = Sniper(
  File "C:\Users\User\MCsniperPY\mcsniperpy\sniper.py", line 23, in __init__
    connector=aiohttp.TCPConnector(limit=300),
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp-4.0.0a1-py3.9-win-amd64.egg\aiohttp\connector.py", line 708, in __init__
    super().__init__(keepalive_timeout=keepalive_timeout,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp-4.0.0a1-py3.9-win-amd64.egg\aiohttp\connector.py", line 207, in __init__
    loop = get_running_loop()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp-4.0.0a1-py3.9-win-amd64.egg\aiohttp\helpers.py", line 276, in get_running_loop
    raise RuntimeError("The object should be created from async function")
RuntimeError: The object should be created from async function
```

**Comment by Kqzz** [comment]
Thanks for bringing this to my attention. Will look into it.

**Comment by Kqzz** [comment]
Going to need more system information. I can't reproduce this.

**Comment by overestimate** [comment]
Hol up, will edit this comment

**Comment by Kqzz** [comment]
What python version?

**Comment by overestimate** [comment]
Python 3.9, HEAD was at dc6b7f1ce29f3481922c10a5ae384f6d29983f6d at time of error
